name: C/C++ CI with Coverage and End-to-End Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        make
        make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ bd43dfc1-4d99-4ec0-bba4-c26207bf05c4 }}  # Replace with your Codecov token
        file: ./coverage.xml  # Path to your coverage report file
        flags: unittests  # Optional: Specify flags if you have multiple coverage reports
        name: codecov-merge-coverage  # Optional: Custom name for the upload
        fail_ci_if_error: true  # Optional: Fail the CI build if uploading fails

